spring.application.name=api-gateway
server.port=8080

# ================= EUREKA =================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ================= GATEWAY SETTINGS =================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ================= ROUTES =================
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=CircuitBreaker=name=userServiceCB,fallbackUri=forward:/fallback/user
spring.cloud.gateway.routes[0].filters[1]=RequestRateLimiter=redis-rate-limiter.replenishRate=5,redis-rate-limiter.burstCapacity=10,key-resolver=#{@userKeyResolver}

spring.cloud.gateway.routes[1].id=vault-service
spring.cloud.gateway.routes[1].uri=lb://VAULT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/vault/**
spring.cloud.gateway.routes[1].filters[0]=CircuitBreaker=name=vaultServiceCB,fallbackUri=forward:/fallback/vault
spring.cloud.gateway.routes[1].filters[1]=RequestRateLimiter=redis-rate-limiter.replenishRate=10,redis-rate-limiter.burstCapacity=20,key-resolver=#{@userKeyResolver}

spring.cloud.gateway.routes[2].id=generator-service
spring.cloud.gateway.routes[2].uri=lb://GENERATOR-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/generator/**
spring.cloud.gateway.routes[2].filters[0]=CircuitBreaker=name=generatorServiceCB,fallbackUri=forward:/fallback/generator

spring.cloud.gateway.routes[3].id=security-service
spring.cloud.gateway.routes[3].uri=lb://SECURITY-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/security/**
spring.cloud.gateway.routes[3].filters[0]=CircuitBreaker=name=securityServiceCB,fallbackUri=forward:/fallback/security

spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/notifications/**

# ================= RESILIENCE SETTINGS =================
resilience4j.circuitbreaker.instances.userServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userServiceCB.waitDurationInOpenState=10s
