spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:mysql://user-db:3306/user_service_db
spring.datasource.username=root
spring.datasource.password=Aadhi@2002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
