spring.application.name=vault-service
server.port=8082

spring.datasource.url=jdbc:mysql://vault-db:3306/vaultdb
spring.datasource.username=root
spring.datasource.password=Aadhi@2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
